project:
  type: website
  output-dir: docs
  preview:
    port: 7209

website:
  title: "Feaster & Balise Lab"
  favicon: /static/favicon.ico
  back-to-top-navigation: true
  
  navbar:
    right:
    # using the folder/index.qmd method displays nicer in the browser bar :)
      - href: index/index.qmd
        text: Home
      - href: people/index.qmd
        text: People
      - href: projects/index.qmd
        text: Projects
      - href: products/index.qmd
        text: Products

format:
  html:
    theme: styles.scss
    toc: true
    # include-in-header: 
    #   - text: |
    #       value: |
    #         <link href="https://cdn.miami.edu/_assets-common/css/umiami.css?version=1.7" rel="stylesheet" type="text/css"/>
    #         <link href="https://cdn.miami.edu/_assets-common/css/generic.css?version=1.7" rel="stylesheet" type="text/css"/>
    #         <link href="https://cdn.miami.edu/_assets-common/library/beautifuldata/beautifuldata.css" rel="stylesheet" type="text/css"/>
    #         <link href="https://www.publichealth.med.miami.edu/_assets/css/theme.css" rel="stylesheet" type="text/css"/>
    #         <link href="https://cdn.miami.edu/_assets-common/css/print.css" media="print" rel="stylesheet" type="text/css"/>
    #         <script src="https://cdn.miami.edu/_assets-common/js/modernizr.js" type="text/javascript"></script>
