project:
  type: website

website:
  title: "Feaster & Balise Lab"
  favicon: /static/favicon.ico
  
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: projects.qmd
        text: Projects
      - href: products.qmd
        text: Products

format:
  html:
    theme: styles.scss
    toc: true



